//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KavakoWebBotTools.Elements {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KOS_Compliance {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KOS_Compliance() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KavakoWebBotTools.Elements.KOS_Compliance", typeof(KOS_Compliance).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div[@id=&apos;click-info-card&apos;]/ul/div/p[contains(text(),&apos;.
        /// </summary>
        internal static string Funnel_Bandeja {
            get {
                return ResourceManager.GetString("Funnel_Bandeja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div/button.
        /// </summary>
        internal static string Funnel_Ficha_GuardarCambios {
            get {
                return ResourceManager.GetString("Funnel_Ficha_GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //header/mat-icon.
        /// </summary>
        internal static string Funnel_Ficha_IconoCerrar {
            get {
                return ResourceManager.GetString("Funnel_Ficha_IconoCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div[@id=&apos;click-info-card&apos;]/ul/div/p[contains(text(),&apos;.
        /// </summary>
        internal static string FunnelAdmin_BandejaResultados {
            get {
                return ResourceManager.GetString("FunnelAdmin_BandejaResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //input[@type=&apos;search&apos;].
        /// </summary>
        internal static string FunnelAdmin_Buscar {
            get {
                return ResourceManager.GetString("FunnelAdmin_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div/button.
        /// </summary>
        internal static string FunnelAdmin_Ficha_GuardarCambios {
            get {
                return ResourceManager.GetString("FunnelAdmin_Ficha_GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //header/mat-icon.
        /// </summary>
        internal static string FunnelAdmin_Ficha_IconoCerrar {
            get {
                return ResourceManager.GetString("FunnelAdmin_Ficha_IconoCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div/div/label/select.
        /// </summary>
        internal static string FunnelAdmin_Ficha_Investigador {
            get {
                return ResourceManager.GetString("FunnelAdmin_Ficha_Investigador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //select.
        /// </summary>
        internal static string FunnelAdmin_ListaBuscarPor {
            get {
                return ResourceManager.GetString("FunnelAdmin_ListaBuscarPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div[@id=&apos;click-info-card&apos;]/ul/li[2]/span[contains(text(),&apos;.
        /// </summary>
        internal static string Investigacion_Bandeja {
            get {
                return ResourceManager.GetString("Investigacion_Bandeja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&apos;main-content&apos;]/div/div[2]/div/div/app-stepper/div/span[1]/a.
        /// </summary>
        internal static string Investigacion_TC_IconoTC {
            get {
                return ResourceManager.GetString("Investigacion_TC_IconoTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&apos;mat-radio-3&apos;]/label/div[2].
        /// </summary>
        internal static string Investigacion_VIN_CoincideConChasis_No {
            get {
                return ResourceManager.GetString("Investigacion_VIN_CoincideConChasis_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&apos;mat-radio-2&apos;]/label/div[2].
        /// </summary>
        internal static string Investigacion_VIN_CoincideConChasis_Si {
            get {
                return ResourceManager.GetString("Investigacion_VIN_CoincideConChasis_Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //span[contains(text(),&apos;SIN CARNET&apos;)].
        /// </summary>
        internal static string Investigacion_VIN_CoincideConChasis_SinCarnet {
            get {
                return ResourceManager.GetString("Investigacion_VIN_CoincideConChasis_SinCarnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //span[contains(text(),&apos;SIN CHASIS&apos;)].
        /// </summary>
        internal static string Investigacion_VIN_CoincideConChasis_SinChasis {
            get {
                return ResourceManager.GetString("Investigacion_VIN_CoincideConChasis_SinChasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div[@id=&apos;main-content&apos;]/div/app-step-one/div/div[2]/app-question-form/form/div/div/app-input-copy-btn/label/input.
        /// </summary>
        internal static string Investigacion_VIN_EscribeNumeroVIN {
            get {
                return ResourceManager.GetString("Investigacion_VIN_EscribeNumeroVIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&apos;main-content&apos;]/div/div[2]/div/div/app-stepper/div/span[1]/a.
        /// </summary>
        internal static string Investigacion_VIN_IconoVin {
            get {
                return ResourceManager.GetString("Investigacion_VIN_IconoVin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&apos;check-question-two-link&apos;]/label/span.
        /// </summary>
        internal static string Investigacion_VIN_RAPI_LinkNoAbre {
            get {
                return ResourceManager.GetString("Investigacion_VIN_RAPI_LinkNoAbre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&apos;main-content&apos;]/div/app-step-one/div/div[2]/app-question-form/form/div[3]/app-upload-btn/button/div.
        /// </summary>
        internal static string Investigacion_VIN_RAPI_TieneReporteRoboIlicito_CargarRespaldoRAPI {
            get {
                return ResourceManager.GetString("Investigacion_VIN_RAPI_TieneReporteRoboIlicito_CargarRespaldoRAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&apos;mat-radio-24&apos;]/label/div[2].
        /// </summary>
        internal static string Investigacion_VIN_RAPI_TieneReporteRoboIlicito_No {
            get {
                return ResourceManager.GetString("Investigacion_VIN_RAPI_TieneReporteRoboIlicito_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&apos;btn-shared-question-form-inspection&apos;].
        /// </summary>
        internal static string Investigacion_VIN_RAPI_TieneReporteRoboIlicito_RechazarInspeccion {
            get {
                return ResourceManager.GetString("Investigacion_VIN_RAPI_TieneReporteRoboIlicito_RechazarInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&apos;mat-radio-23&apos;]/label/div[2].
        /// </summary>
        internal static string Investigacion_VIN_RAPI_TieneReporteRoboIlicito_Si {
            get {
                return ResourceManager.GetString("Investigacion_VIN_RAPI_TieneReporteRoboIlicito_Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //button[@type=&apos;button&apos;]/div[1].
        /// </summary>
        internal static string Investigacion_VIN_REPUVE_CargarRespaldoREPUVE {
            get {
                return ResourceManager.GetString("Investigacion_VIN_REPUVE_CargarRespaldoREPUVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div[@id=&apos;main-content&apos;]/div/app-step-one/div/div[2]/app-question-form/form/div[2]/div[3]/div[2]/label/select.
        /// </summary>
        internal static string Investigacion_VIN_REPUVE_ExistePlacaRegistrada_Estado {
            get {
                return ResourceManager.GetString("Investigacion_VIN_REPUVE_ExistePlacaRegistrada_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[text()=&apos;¿EXISTE UNA PLACA REGISTRADA?&apos;]//following::*[text()=&apos;NO&apos;][1].
        /// </summary>
        internal static string Investigacion_VIN_REPUVE_ExistePlacaRegistrada_No {
            get {
                return ResourceManager.GetString("Investigacion_VIN_REPUVE_ExistePlacaRegistrada_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div[2]/app-input-copy-btn/label/input.
        /// </summary>
        internal static string Investigacion_VIN_REPUVE_ExistePlacaRegistrada_Placa {
            get {
                return ResourceManager.GetString("Investigacion_VIN_REPUVE_ExistePlacaRegistrada_Placa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[text()=&apos;¿EXISTE UNA PLACA REGISTRADA?&apos;]//following::*[text()=&apos;SÍ&apos;][1].
        /// </summary>
        internal static string Investigacion_VIN_REPUVE_ExistePlacaRegistrada_Si {
            get {
                return ResourceManager.GetString("Investigacion_VIN_REPUVE_ExistePlacaRegistrada_Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&apos;check-question-two-not-open&apos;]/label/span[contains(text(),&apos;LINK NO ABRE&apos;)].
        /// </summary>
        internal static string Investigacion_VIN_REPUVE_LinkNoAbre {
            get {
                return ResourceManager.GetString("Investigacion_VIN_REPUVE_LinkNoAbre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[contains(text(),&apos;¿EL MODELO, LA VERSIÓN Y EL AÑO COTIZADO COINCIDE&apos;)]//following::*[text()=&apos;NO&apos;][1].
        /// </summary>
        internal static string Investigacion_VIN_REPUVE_ModeloCoincideConREPUVE_No {
            get {
                return ResourceManager.GetString("Investigacion_VIN_REPUVE_ModeloCoincideConREPUVE_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[contains(text(),&apos;¿EL MODELO, LA VERSIÓN Y EL AÑO COTIZADO COINCIDE&apos;)]//following::*[text()=&apos;SÍ&apos;][1].
        /// </summary>
        internal static string Investigacion_VIN_REPUVE_ModeloCoincideConREPUVE_Si {
            get {
                return ResourceManager.GetString("Investigacion_VIN_REPUVE_ModeloCoincideConREPUVE_Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&apos;btn-shared-question-form-reject&apos;].
        /// </summary>
        internal static string Investigacion_VIN_REPUVE_TieneReporteRoboIlicito_BotonRechazar {
            get {
                return ResourceManager.GetString("Investigacion_VIN_REPUVE_TieneReporteRoboIlicito_BotonRechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[text()=&apos;¿TIENE REPORTE DE ROBO ILÍCITO?&apos;]//following::*[text()=&apos;NO&apos;][1].
        /// </summary>
        internal static string Investigacion_VIN_REPUVE_TieneReporteRoboIlicito_No {
            get {
                return ResourceManager.GetString("Investigacion_VIN_REPUVE_TieneReporteRoboIlicito_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[text()=&apos;¿TIENE REPORTE DE ROBO ILÍCITO?&apos;]//following::*[text()=&apos;SÍ&apos;][1].
        /// </summary>
        internal static string Investigacion_VIN_REPUVE_TieneReporteRoboIlicito_Si {
            get {
                return ResourceManager.GetString("Investigacion_VIN_REPUVE_TieneReporteRoboIlicito_Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&apos;btn-shared-question-form-next&apos;].
        /// </summary>
        internal static string Investigacion_VIN_Siguiente {
            get {
                return ResourceManager.GetString("Investigacion_VIN_Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div/span[4].
        /// </summary>
        internal static string PestanhiaNavegacionDocumentos {
            get {
                return ResourceManager.GetString("PestanhiaNavegacionDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div/span[2].
        /// </summary>
        internal static string PestanhiaNavegacionFunnel {
            get {
                return ResourceManager.GetString("PestanhiaNavegacionFunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div/span[1].
        /// </summary>
        internal static string PestanhiaNavegacionFunnelAdmin {
            get {
                return ResourceManager.GetString("PestanhiaNavegacionFunnelAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div/span[3].
        /// </summary>
        internal static string PestanhiaNavegacionInvestigacion {
            get {
                return ResourceManager.GetString("PestanhiaNavegacionInvestigacion", resourceCulture);
            }
        }
    }
}
